# Generated by Django 4.1 on 2023-09-17 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('Full_Name', models.CharField(max_length=50)),
                ('Phone', models.CharField(max_length=50)),
                ('ID', models.CharField(max_length=50)),
                ('Email', models.CharField(max_length=50)),
                ('University', models.CharField(max_length=50)),
                ('School', models.CharField(max_length=50)),
                ('Department', models.CharField(max_length=50)),
                ('Block_Dorm', models.CharField(max_length=50)),
                ('Acadamics', models.CharField(max_length=50)),
            ],
        ),
    ]
